apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: bookapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: zubairk27/book-app-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: mongodb://host.minikube.internal:27017/bookstore
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: bookapp
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30001
