name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Backend Image
        run: |
          docker build -t zubairk27/book-app-backend:latest ./backend
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
          docker push zubairk27/book-app-backend:latest

      - name: Build and Push Frontend Image
        run: |
          docker build -t zubairk27/book-app-frontend:latest ./frontend
          docker push zubairk27/book-app-frontend:latest

      - name: Deploy Backend
        run: kubectl apply -f app/backend-deployment.yaml -n bookapp

      - name: Deploy Frontend
        run: kubectl apply -f app/frontend-deployment.yaml -n bookapp

      - name: Verify Deployment
        run: kubectl get all -n bookapp
